package net.alhrairyalbraa.kalmani.utils

data class Mapping(
    val weekMap: Map<String, String> = mapOf(
        "saturday" to "السبت",
        "sunday" to "الأحد",
        "monday" to "الإثنين",
        "tuesday" to "الثلاثاء",
        "wednesday" to "الأربعاء",
        "thursday" to "الخميس",
        "friday" to "الجمعة"
    ), val numbersMap: Map<String, String> = mapOf(
        "zero" to "صفر",
        "one" to "واحد - 1",
        "two" to "اثنين - 2",
        "three" to "ثلاثة - 3",
        "four" to "أربعة - 4",
        "five" to "خمسة - 5",
        "six" to "ستة - 6",
        "seven" to "سبعة - 7",
        "eight" to "ثمانية - 8",
        "nine" to "تسعة - 9",
        "ten" to "عشرة - 10",
        "eleven" to "إحدى عشر - 11",
        "twelve" to "إثنى عشر - 12",
        "thirteen" to "ثلاثة عشر - 13",
        "fourteen" to "أربعة عشر - 14",
        "fifteen" to "خمسة عشر - 15",
        "sixteen" to "ستة عشر - 16",
        "seventeen" to "سبعة عشر - 17",
        "eighteen" to "ثمانية عشر - 18",
        "nineteen" to "تسعة عشر - 19",
        "twenty" to "عشرون - 20"
    ), val lettersMap: Map<String, String> = mapOf(
        "Ain" to "عين - ع",
        "Al" to "ألف - أ",
        "Alef" to "ألف - أ",
        "Beh" to "باء - ب",
        "Dad" to "ضاد - ض",
        "Dal" to "دال - د",
        "Feh" to "فاء - ف",
        "Ghain" to "غين - غ",
        "Hah" to "حاء - ح",
        "Jeem" to "جيم - ج",
        "Kaf" to "كاف - ك",
        "Khah" to "خاء - خ",
        "Lam" to "لام - ل",
        "Meem" to "ميم - م",
        "Noon" to "نون - ن",
        "Qaf" to "قاف - ق",
        "Reh" to "راء - ر",
        "Sad" to "صاد - ص",
        "Seen" to "سين - س",
        "Sheen" to "شين - ش",
        "Tah" to "طاء - ط",
        "Teh" to "تاء - ت",
        "Thal" to "ذال - ذ",
        "Theh" to "ثاء - ث",
        "Waw" to "واو - و",
        "Yeh" to "ياء- ي",
        "Zah" to "ظاء - ظ",
        "Zain" to "زاي - ز",
        "Heh" to "هاء - ه"
    ), val lettersMap3: Map<String, String> = mapOf(
        "Ain" to "ع",
        "Al" to "أ",
        "Alef" to "ا",
        "Beh" to "ب",
        "Dad" to "ض",
        "Dal" to "د",
        "Feh" to "ف",
        "Ghain" to "غ",
        "Hah" to "ح",
        "Jeem" to "ج",
        "Kaf" to " ك",
        "Khah" to "خ",
        "Lam" to "ل",
        "Meem" to "م",
        "Noon" to "ن",
        "Qaf" to "ق",
        "Reh" to "ر",
        "Sad" to "ص",
        "Seen" to "س",
        "Sheen" to "ش",
        "Tah" to "ط",
        "Teh" to "ت",
        "Thal" to "ذ",
        "Theh" to "ث",
        "Waw" to "و",
        "Yeh" to "ي",
        "Zah" to "ظ",
        "Zain" to "ز",
        "Heh" to "ه",
        "space" to " ",
        "nothing" to ""
    ), val lettersMap2: Map<Int, String> = mapOf(
        0 to "Ain",
        1 to "Alef",
        2 to "Beh",
        3 to "Dad",
        4 to "Dal",
        5 to "Delete",
        6 to "Feh",
        7 to "Ghain",
        8 to "Hah",
        9 to "Heh",
        10 to "Jeem",
        11 to "Kaf",
        12 to "Khah",
        13 to "Lam",
        14 to "Meem",
        15 to "Noon",
        16 to "Qaf",
        17 to "Reh",
        18 to "Sad",
        19 to "Seen",
        20 to "Sheen",
        21 to "Tah",
        22 to "Teh",
        23 to "Thal",
        24 to "Theh",
        25 to "Waw",
        26 to "Yeh",
        27 to "Zah",
        28 to "Zain",
        29 to "nothing",
        30 to "space"
    ), val familyMap: Map<String, String> = mapOf(
        "man_or_father" to "أب",
        "mother" to "أم",
        "grandpa" to "جد",
        "grandma" to "جدة",
        "boy" to "ولد",
        "girl" to "بنت",
        "bro" to "أخ",
        "sister" to "أخت",
        "Baba" to "بابا",
        "Mama" to "ماما",
        "woman" to "امرأة",
        "uncle" to "عم",
        "aunt" to "عمة",
        "family" to "أسرة",
        "bros" to "أخوات",
        "baby" to "رضيع"
    ), val pronounsMap: Map<String, String> = mapOf(
        "" to "أنا",
        "" to "أنت",
        "" to "نحن",
        "" to "هؤلاء",
        "" to "هاتان",
        "" to "هاذان",
        "" to "هذا",
        "" to "هذه",
        "" to "هما",
        "" to "هو",
        "" to "هي"
    ), val wordsMap: Map<String, String> = mapOf(
        "fine_alhamdullah" to "بخير الحمدلله",
        "going" to "ذاهب",
        "How are you" to "كيف حالك",
        "I" to "أنا",
        "Peace On You" to "السلام عليكم",
        "Where" to "أين",
        "You" to "أنت",
        "Hi" to "مرحبا",
        "whats_ur_birthday" to "ما تاريخ ميلادك؟",
        "Whats_your_name" to "ما أسمك؟",
        "wheres_ur_house" to "أين تسكن؟",
        "Thanks" to "شكرا"
    ), val wordsClassMap: Map<Int, String> = mapOf(
        0 to "Alhamdullah",
        1 to "all",
        2 to "Baba",
        3 to "Basis",
        4 to "because",
        5 to "Boy",
        6 to "Brave",
        7 to "Confused",
        8 to "conversation",
        9 to "Crying",
        10 to "daily",
        11 to "danger",
        12 to "disagree with",
        13 to "effort",
        14 to "Egypt",
        15 to "Enters",
        16 to "Excelent",
        17 to "explanation",
        18 to "Fasting",
        19 to "Female",
        20 to "First",
        21 to "fuel",
        22 to "Gift",
        23 to "good bye",
        24 to "Happy",
        25 to "hates",
        26 to "hears",
        27 to "Help",
        28 to "Humanity",
        29 to "hungry",
        30 to "I",
        31 to "ignorance",
        32 to "immediately",
        33 to "Intelligent",
        34 to "Last",
        35 to "leader",
        36 to "Liar",
        37 to "Loves",
        38 to "male",
        39 to "model",
        40 to "Muslim",
        41 to "my home land",
        42 to "no",
        43 to "obvious",
        44 to "Old",
        45 to "Palestine",
        46 to "rejection",
        47 to "Right",
        48 to "sleeps",
        49 to "Somkes",
        50 to "symposium",
        51 to "Tea",
        52 to "teacher",
        53 to "Thanks",
        54 to "time",
        55 to "to boycott",
        56 to "to go",
        57 to "to live",
        58 to "to spread",
        59 to "Toilet",
        60 to "trap",
        61 to "University",
        62 to "victory",
        63 to "walks",
        64 to "Where",
        65 to "wheres_ur_house",
        66 to "Window",
        67 to "Winter",
        68 to "yes"
    )
)
